### ISSUE TITLE
Add support of OpenType features (tabular numerals, etc)

### ISSUE THREAD

**Issue by alexkolodko** [paulzi/svg-text-to-path#10]
I used OpenType features in css (tabular numbers or alternates stylistic set). But script replaces alternate symbols with the ordinary. [Demo](https://youtube.com/shorts/mEmv4VkW2zw?feature=share): tabular symbols "1" at the top replaced to ordinary.

Can you add support of OT features to maybe you know how works with alternates?

**Comment by paulzi** [comment]
Closed in v2.0.0
