### ISSUE TITLE
Support for `font-stretch`

### ISSUE THREAD

**Issue by MingweiSamuel** [paulzi/svg-text-to-path#12]
The `font-stretch` css property allows different versions of a font to be used for wider or narrower characters.

    font-stretch:
    ultra-condensed 50%
    extra-condensed 62.5%
    condensed       75%
    semi-condensed  87.5%
    normal          100%
    semi-expanded   112.5%
    expanded        125%
    extra-expanded  150%
    ultra-expanded  200%

What would the steps be for supporting this in svg-text-to-path?

**Comment by paulzi** [comment]
I tried to reproduce, this property is not supported by any browsers for svg `<text>` elements.
