### ISSUE TITLE
font-family with multiple languages

### ISSUE THREAD

**Issue by willyou** [paulzi/svg-text-to-path#14]
Hello there, I would like to know if I can use `font-family` with multiple values.
For instance, I have a string with KR and English like `Adidas with 안녕하세요` .
I set `font-family` to `Robot, Noto Sans KR`

But the KR string failed to demonstrate on the SVG text.
Is there any workaround I can follow? Thanks!

**Comment by willyou** [comment]
This feature means a lot to us.
Is there any way that we can donate this project a bit to speed up the feature development?
Thanks in advance.

**Comment by paulzi** [comment]
Hello! I will try to do this in the next 2-3 weeks.

**Comment by willyou** [comment]
Thanks, let me know if you need anything else, I am happy to help.
Currently, we need to separate different languages into different `<tspan/>` with different `font-family`.
So it would be great to have this feature.

**Comment by paulzi** [comment]
Small report. Support for multilanguage resulted in a fairly large rework worthy of a major version.
The [font selection specification](https://drafts.csswg.org/css-fonts-4/#font-matching-algorithm) alone is pretty hard)
In general, it will take a little longer than expected, but there will be support for variable fonts, and much more.

**Comment by paulzi** [comment]
Closed in v2.0.0

**Comment by willyou** [comment]
Hey, @paulzi 
Thanks a lot! I am going to give it a shot recently, 
Before proceeding, I want to donate first, but it is RUB currency; I am unsure if I can use it with my credit card in Taiwan.
Do you have Paypal or another service I can send money to?

**Comment by paulzi** [comment]
Hi! You can pass url of ttf font via `fonts` option.


```javascript
let session = new Session(svg, {
  fonts: {
    'GoNOTO': [
      {
        wdth: 400,
        ital: 0,
        source: 'https://example.com/fonts/GoNOTO.ttf',
      }
    ],
  },
  googleApiKey: 'key',
})
```

Yes, Russian users are now under sanctions, so donations cannot be sent yet.
