### ISSUE TITLE
Every svg I generate got display none inside svg tag

### ISSUE THREAD

**Issue by willyou** [paulzi/svg-text-to-path#15]
This is the svg code I got,
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 500 500" style="display: none;">`

My code is just:

```
let session = new Session(
        `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 500 500">
            <style> text{ font-size:42px}</style>
      <text x="20" y="25" font-family="Roboto,Noto Sans KR,Noto Sans TC, Helvetica">sà-wàt-dee안녕하세요i Bas안녕하세요ic 可是 343sample</text>
      </svg>`,
        {
          googleApiKey: 'key',
        }
      );
      let stat = await session.replaceAll();
      let out = session.getSvgString();
```

Could you try on your end to see if it is an issue?
Thanks!

**Comment by paulzi** [comment]
Fix in v2.0.1.
Don't forget to do a `session.destroy()` after doing the replacement, because to manipulate the svg parsed from string in the browser it append a hidden `<div>` to DOM.
