### ISSUE TITLE
Problem by running svg-text-to-path via php exec

### ISSUE THREAD

**Issue by MichaelZiegler** [paulzi/svg-text-to-path#22]
Hello and thank you very much for your great svg-text-to-path-tool!

We are working on a php-script that should start svg-text-to-path via the exec- or shell_exec-function of php.
We testet code like 
`$output = shell_exec('cat '.$inputpath.' | svg-text-to-path -k -c svg-create.conf >'.$outputpath);`
or
`$output = shell_exec('svg-text-to-path -k -c svg-create.conf -o '.$outputpath.' '.$inputpath);`     
      
In both cases it seems as if svg-text-to-path doesn't get the inputfile. It creates an output-file, but there is just this line inside:
`<parsererror xmlns="http://www.mozilla.org/newlayout/xml/parsererror.xml">1:0: document must contain a root element.</parsererror>`

If we run the same function (of course with the input- and output-path instead of the vars) everything works perfect.

Do you have any idea, what we are doing wrong or how we can use your tool in that way?

**Comment by paulzi** [comment]
Hello, Michael!
This is not a svg-text-to-path bug, but a feature of [work pipes in php](https://stackoverflow.com/questions/16733918/how-to-use-pipe-in-php-exec).
You can use the following use cases with php:
1) Simply use `-o` key: `$output = shell_exec("svg-text-to-path -k -c svg-create.conf -o $outpath $inputpath");`
2) Add braces: `shell_exec("(command1 | command2)");`
3) If you realy want to use pipes, you need somethink like this:
```php
$proc = proc_open('svg-text-to-path', [
    0 => ['pipe', 'w'],
    1 => ['pipe', 'w'],
], $pipes);
$stdout = stream_put_contents($pipes[0], '<svg>...</svg>');
fclose($pipes[0]);
$stdout = stream_get_contents($pipes[1]);
fclose($pipes[1]);
$code = proc_close($proc);
return [$stdout, $code];
```

**Comment by MichaelZiegler** [comment]
Hello Paulzi,
thank you very much for your extremly fast answer.
But I'm very sorry, this is not a solution for us.

As described, we tried your variant 1. When we run it via `shell_exec` we get an almost empty file with the parse error inside it. When we take the same command and run it in a bash terminal everything works correct. During our tests we also used an incorrect path as `$inputpath` and that leads us to the same file with the same error message.
So it seems as if your tool don't receives the inputpath by running the tool via `shell_exec`.

We used `shell_exec` for other applications in the same way without any problems, so we believe this is anything specific to your tool. Do you have any idea or an exemple how to run your tool from a php (in our case laravel) project?

Best regards
Michael

**Comment by paulzi** [comment]
I'm try my first option. Everything completed successfully:
```
www-data@paulzi-dev-server:~$ php -r "var_dump(shell_exec('svg-text-to-path -o out.svg in.svg'));"
string(88) "Used fonts:
  'Bad Script': 1 variants, 12 chars
Successfuly replaced 1 of 1 text nodes
"
```
Check that the file paths are correct.
