### ISSUE TITLE
Alignment baseline middle is not supported

### ISSUE THREAD

**Issue by iziorama** [paulzi/svg-text-to-path#4]
Alignment-baseline="middle" SVG property ignored while conversions.

**Comment by paulzi** [comment]
The property `aligment-baseline` is not supported now for two reasons:
1) this property is not supported in firefox
2) this is a complete analogue for property `dominant-baseline`

In future version, I can make `aligment-baseline` as alias of `dominant-baseline`.

**Comment by iziorama** [comment]
Just tested. You are right `aligment-baseline` works as a charm 💪
