### ISSUE TITLE
Can't convert local font

### ISSUE THREAD

**Issue by diego-tentor** [paulzi/svg-text-to-path#9]
I'm not sure if the inclusion of a local source is configured correctly
Thanks
![imagen](https://user-images.githubusercontent.com/64558964/171756316-7d7d350d-6876-4539-9e17-46aedf4155c8.png)
![imagen](https://user-images.githubusercontent.com/64558964/171756560-0220083f-a116-4582-a7a4-c506fd6d9689.png)

**Comment by paulzi** [comment]
Hi! See the [documentation](See the documentation for how to write matches correctly) for how to write fintMap correctly:
```json
"fontMap": {
  "Alone": {
    "400": "http://url"
  }
}
```
400 - is font weight, without italic

**Comment by paulzi** [comment]
fontMap is config property, not package.json
```js
SvgTextToPath.replaceAll(document.querySelector('svg'), {
          handlers: [SvgTextToPath.handlers.map],
          fonrMap: {},
          group: true
        })
```
